"""
Module 2.2: Traffic-to-Pycontrails Adapter
A utility module imported by Loop 3 (Physics). It takes the cleaned DataFrames 
generated by the `traffic` library and adapts them into strictly formatted 
`pycontrails.Flight` objects ready for the Cocip model.
"""
import pandas as pd
import logging
from pycontrails import Flight

def dataframe_to_pycontrails(df_flight: pd.DataFrame, typecode: str = "UNKNOWN") -> Flight:
    """
    Transforms a single cleaned flight DataFrame into a pycontrails Flight object.
    
    Args:
        df_flight (pd.DataFrame): Cleaned trajectory for a SINGLE flight.
        typecode (str): The aircraft type designator (e.g., 'B777'). Crucial for PSFlight.
        
    Returns:
        Flight: A pycontrails Flight object.
    """
    if df_flight is None or df_flight.empty:
        logging.warning("Empty dataframe provided to adapter.")
        return None
        
    # Extract metadata from the first row
    icao24 = df_flight['icao24'].iloc[0] if 'icao24' in df_flight.columns else 'UNK'
    callsign = df_flight['callsign'].iloc[0] if 'callsign' in df_flight.columns else 'UNK'
    flight_id = df_flight['flight_id'].iloc[0] if 'flight_id' in df_flight.columns else f"{icao24}_{callsign}"
    firstseen = df_flight['firstseen'].iloc[0] if 'firstseen' in df_flight.columns else None
    lastseen = df_flight['lastseen'].iloc[0] if 'lastseen' in df_flight.columns else None

    # Resolve typecode if not passed or "UNKNOWN"
    if typecode == "UNKNOWN" and 'typecode' in df_flight.columns:
        typecode = df_flight['typecode'].iloc[0]

    # 1. Map columns back to Pycontrails API
    # Pycontrails requires: time, latitude, longitude, altitude (in meters)
    rename_map = {
        'timestamp': 'time',
        'groundspeed': 'gs',
        'track': 'heading',
        'vertical_rate': 'rocd',
    }
    
    df_pc = df_flight.rename(columns=rename_map).copy()
    
    # Drop EKF projection specific columns to match standard PyContrails schemas
    ekf_cols = ['x', 'y', 'track_unwrapped']
    df_pc = df_pc.drop(columns=[c for c in ekf_cols if c in df_pc.columns], errors='ignore')
    
    # Explicitly drop true_airspeed / tas / velocity columns so that PSFlight
    # calculates True Airspeed (TAS) manually using groundspeed (gs) and wind.
    airspeed_cols = ['true_airspeed', 'tas', 'velocity']
    df_pc = df_pc.drop(columns=[c for c in airspeed_cols if c in df_pc.columns], errors='ignore')
    
    # 2. Build Pycontrails Attributes Dictionary
    attrs = {
        "flight_id": flight_id,
        "aircraft_type": typecode,  # PSFlight will use this to look up BADA/aircraft parameters
        "icao24": icao24,
        "callsign": callsign,
    }
    if pd.notna(firstseen):
        attrs["firstseen"] = firstseen
    if pd.notna(lastseen):
        attrs["lastseen"] = lastseen
    
    # 3. Instantiate and return the Pycontrails Flight
    try:
        # Pass attrs as kwargs to store them as Flight attributes.
        # Pass drop_duplicated_times=True and crs="EPSG:4326" for safety.
        pc_flight = Flight(data=df_pc, drop_duplicated_times=True, crs="EPSG:4326", **attrs)
        return pc_flight
    except Exception as e:
        logging.error(f"Failed to create pycontrails.Flight for {flight_id}: {e}")
        return None

def extract_flights_from_parquet(parquet_path: str) -> dict:
    """
    Helper function to load a clean Parquet file containing multiple flights,
    and yield them as individual DataFrames grouped by flight_id.
    
    Returns:
        dict: A dictionary mapping flight_id -> pd.DataFrame
    """
    df = pd.read_parquet(parquet_path)
    flight_groups = {}
    
    for flight_id, group_df in df.groupby('flight_id'):
        flight_groups[flight_id] = group_df.copy()
        
    return flight_groups