"""
Performance & Drift Analyzer Devtool

Analyzes Star-Schema execution tables (call_sites + invocations) generated by
trace_correlator.py. Detects:
    1. Memory baseline drift & persistent leaks across loop iterations
    2. OS Thrashing & Pagefile offload signatures (page faults vs flat RAM)
    3. GC Sawtooth patterns & collection cycle residuals
    4. Call site execution distributions (mean, median, P95, max)
    5. Multi-run comparative diffs (e.g. Standard Mode vs. Low-Memory Mode)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


def load_dataset(data_dir: Path) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Load call_sites and invocations from parquet (or fallback to csv)."""
    data_dir = Path(data_dir)
    parquet_sites = data_dir / "call_sites.parquet"
    parquet_inv = data_dir / "invocations.parquet"

    if parquet_sites.exists() and parquet_inv.exists():
        df_sites = pd.read_parquet(parquet_sites)
        df_inv = pd.read_parquet(parquet_inv)
    else:
        csv_sites = data_dir / "call_sites.csv"
        csv_inv = data_dir / "invocations.csv"
        if not (csv_sites.exists() and csv_inv.exists()):
            raise FileNotFoundError(f"Missing star-schema tables in {data_dir}")
        df_sites = pd.read_csv(csv_sites)
        df_inv = pd.read_csv(csv_inv)

    return df_sites, df_inv


def analyze_distributions(df_sites: pd.DataFrame, df_inv: pd.DataFrame) -> pd.DataFrame:
    """Compute per-call-site invocation statistics."""
    merged = df_inv.merge(df_sites, on="site_id", how="left")

    agg_rows = []
    for site_id, group in merged.groupby("site_id"):
        first_row = group.iloc[0]
        durations = group["duration_ms"].to_numpy()
        ram_deltas = group["ram_delta_mb"].to_numpy()
        faults = group["page_faults_delta"].to_numpy() if "page_faults_delta" in group.columns else np.zeros(len(group))
        swaps = group["swap_pressure"].to_numpy() if "swap_pressure" in group.columns else np.zeros(len(group))

        agg_rows.append(
            {
                "site_id": site_id,
                "func": first_row["func"],
                "module": first_row["module"],
                "parent_func": first_row["parent_func"],
                "call_count": len(group),
                "total_duration_s": round(float(np.sum(durations)) / 1000.0, 3),
                "mean_ms": round(float(np.mean(durations)), 2),
                "p50_ms": round(float(np.median(durations)), 2),
                "p95_ms": round(float(np.percentile(durations, 95)), 2),
                "max_ms": round(float(np.max(durations)), 2),
                "total_ram_delta_mb": round(float(np.sum(ram_deltas)), 2),
                "peak_ram_mb": round(float(np.max(group["ram_peak_mb"])), 2),
                "mean_swap_pressure": round(float(np.mean(swaps)), 4),
                "total_page_faults": int(np.sum(faults)),
                "pycontrails_boundary": bool(first_row.get("pycontrails_boundary", False)),
            }
        )

    df_dist = pd.DataFrame(agg_rows)
    if not df_dist.empty:
        df_dist.sort_values(by="total_duration_s", ascending=False, inplace=True)
    return df_dist


def detect_memory_drift(
    df_sites: pd.DataFrame,
    df_inv: pd.DataFrame,
    min_invocations: int = 4,
    drift_threshold_mb_per_inv: float = 3.0,
) -> List[Dict[str, any]]:
    """Detect monotonic baseline RAM growth across repeated invocations."""
    merged = df_inv.merge(df_sites, on="site_id", how="left")
    drift_alerts = []

    for site_id, group in merged.groupby("site_id"):
        if len(group) < min_invocations:
            continue

        group_sorted = group.sort_values("inv_idx")
        x = group_sorted["inv_idx"].to_numpy().astype(float)
        y = group_sorted["ram_start_mb"].to_numpy().astype(float)

        if len(x) < 2:
            continue

        # Linear regression
        cov = np.cov(x, y)[0, 1]
        var_x = np.var(x)
        if var_x > 0:
            slope = cov / var_x
            corr = np.corrcoef(x, y)[0, 1] if np.std(y) > 0 else 0.0
            r2 = corr**2
        else:
            slope = 0.0
            r2 = 0.0

        net_drift = float(y[-1] - y[0])

        if slope >= drift_threshold_mb_per_inv and r2 >= 0.5 and net_drift > 20.0:
            first_row = group_sorted.iloc[0]
            # Find earliest significant jump
            jump_idx = 0
            for k in range(1, len(y)):
                if y[k] - y[0] >= 20.0:
                    jump_idx = int(group_sorted.iloc[k]["inv_idx"])
                    break

            drift_alerts.append(
                {
                    "site_id": site_id,
                    "func": first_row["func"],
                    "module": first_row["module"],
                    "parent_func": first_row["parent_func"],
                    "call_count": len(group),
                    "slope_mb_per_inv": round(float(slope), 2),
                    "r2": round(float(r2), 3),
                    "net_drift_mb": round(net_drift, 2),
                    "start_ram_mb": round(float(y[0]), 2),
                    "end_ram_mb": round(float(y[-1]), 2),
                    "divergence_inv_idx": jump_idx,
                }
            )

    drift_alerts.sort(key=lambda x: x["net_drift_mb"], reverse=True)
    return drift_alerts


def detect_thrashing_events(
    df_sites: pd.DataFrame,
    df_inv: pd.DataFrame,
    fault_threshold: int = 500,
    swap_pressure_threshold: float = 0.15,
) -> List[Dict[str, any]]:
    """Identify spans with severe page fault spikes or elevated swap pressure."""
    merged = df_inv.merge(df_sites, on="site_id", how="left")
    thrash_rows = []

    for _, row in merged.iterrows():
        faults = row.get("page_faults_delta", 0)
        swap = row.get("swap_pressure", 0.0)

        if faults >= fault_threshold or swap >= swap_pressure_threshold:
            thrash_rows.append(
                {
                    "site_id": row["site_id"],
                    "func": row["func"],
                    "module": row["module"],
                    "inv_idx": int(row["inv_idx"]),
                    "pid": row["pid"],
                    "start_ts": row["start_ts"],
                    "duration_ms": row["duration_ms"],
                    "ram_peak_mb": row["ram_peak_mb"],
                    "commit_peak_mb": row["commit_peak_mb"],
                    "swap_pressure": row["swap_pressure"],
                    "page_faults_delta": int(faults),
                }
            )

    thrash_rows.sort(key=lambda x: x["page_faults_delta"], reverse=True)
    return thrash_rows


def compare_runs(
    dir_run1: Path,
    dir_run2: Path,
) -> pd.DataFrame:
    """Soft-match call sites between two runs and compute comparative differential metrics."""
    sites1, inv1 = load_dataset(dir_run1)
    sites2, inv2 = load_dataset(dir_run2)

    dist1 = analyze_distributions(sites1, inv1)
    dist2 = analyze_distributions(sites2, inv2)

    # Match on structural key: (func, module, parent_func)
    match_cols = ["func", "module", "parent_func"]
    merged = dist1.merge(dist2, on=match_cols, suffixes=("_run1", "_run2"), how="inner")

    diff_rows = []
    for _, row in merged.iterrows():
        dur1 = row["total_duration_s_run1"]
        dur2 = row["total_duration_s_run2"]
        mean1 = row["mean_ms_run1"]
        mean2 = row["mean_ms_run2"]
        ram1 = row["peak_ram_mb_run1"]
        ram2 = row["peak_ram_mb_run2"]
        faults1 = row["total_page_faults_run1"]
        faults2 = row["total_page_faults_run2"]
        swap1 = row["mean_swap_pressure_run1"]
        swap2 = row["mean_swap_pressure_run2"]

        diff_dur_pct = round(((dur2 - dur1) / max(0.001, dur1)) * 100.0, 1)
        diff_ram_mb = round(ram2 - ram1, 2)
        diff_ram_pct = round(((ram2 - ram1) / max(0.001, ram1)) * 100.0, 1)

        diff_rows.append(
            {
                "func": row["func"],
                "module": row["module"],
                "parent_func": row["parent_func"],
                "calls_r1": int(row["call_count_run1"]),
                "calls_r2": int(row["call_count_run2"]),
                "total_s_r1": dur1,
                "total_s_r2": dur2,
                "diff_dur_pct": diff_dur_pct,
                "mean_ms_r1": mean1,
                "mean_ms_r2": mean2,
                "peak_ram_r1": ram1,
                "peak_ram_r2": ram2,
                "diff_ram_mb": diff_ram_mb,
                "diff_ram_pct": diff_ram_pct,
                "faults_r1": faults1,
                "faults_r2": faults2,
                "swap_r1": swap1,
                "swap_r2": swap2,
            }
        )

    df_diff = pd.DataFrame(diff_rows)
    if not df_diff.empty:
        df_diff.sort_values(by="total_s_r1", ascending=False, inplace=True)
    return df_diff


def generate_markdown_report(
    data_dir: Path,
    compare_dir: Optional[Path] = None,
    output_report: Optional[Path] = None,
) -> str:
    """Generate comprehensive GitHub-flavored Markdown report."""
    data_dir = Path(data_dir)
    df_sites, df_inv = load_dataset(data_dir)

    dist = analyze_distributions(df_sites, df_inv)
    drifts = detect_memory_drift(df_sites, df_inv)
    thrash = detect_thrashing_events(df_sites, df_inv)

    report_lines: List[str] = []
    report_lines.append(f"# Performance & Telemetry Trace Report: `{data_dir.name}`\n")
    report_lines.append(f"- **Data Directory**: `{data_dir}`")
    report_lines.append(f"- **Unique Call Sites**: `{len(df_sites)}`")
    report_lines.append(f"- **Total Invocations Tracked**: `{len(df_inv)}`")
    report_lines.append(f"- **Max Process RAM Observed**: `{df_inv['ram_peak_mb'].max():.2f} MB`")
    report_lines.append(f"- **Max Commit Observed**: `{df_inv['commit_peak_mb'].max():.2f} MB`\n")

    # Section 1: Executive Summary
    report_lines.append("## 1. Executive Performance Summary\n")
    if drifts:
        report_lines.append(
            f"> [!WARNING]\n"
            f"> **Memory Drift Detected**: {len(drifts)} call site(s) exhibit persistent baseline RAM growth.\n"
        )
    else:
        report_lines.append("> [!NOTE]\n> **Memory Baseline Stable**: No persistent monotonic memory drift detected.\n")

    if thrash:
        report_lines.append(
            f"> [!CAUTION]\n"
            f"> **Thrashing / Page Fault Spikes**: {len(thrash)} span(s) exceeded page fault or swap pressure thresholds.\n"
        )

    # Section 2: Top Execution Hotspots
    report_lines.append("## 2. Top Execution Hotspots (by Total Wall-Clock Time)\n")
    report_lines.append("| Function | Module | Parent | Calls | Total (s) | Mean (ms) | P95 (ms) | Peak RAM (MB) | Net ΔRAM (MB) |")
    report_lines.append("|---|---|---|---|---|---|---|---|---|")
    for _, r in dist.head(15).iterrows():
        report_lines.append(
            f"| `{r['func']}` | `{r['module']}` | `{r['parent_func']}` | {r['call_count']} | "
            f"{r['total_duration_s']:.2f}s | {r['mean_ms']:.1f} | {r['p95_ms']:.1f} | "
            f"{r['peak_ram_mb']:.1f} | {r['total_ram_delta_mb']:+.1f} |"
        )
    report_lines.append("")

    # Section 3: Memory Drift Analysis
    report_lines.append("## 3. Memory Drift & Leak Analysis\n")
    if drifts:
        report_lines.append("| Function | Module | Caller | Invocations | Slope (MB/inv) | Net Drift (MB) | Start RAM | End RAM | 1st Jump |")
        report_lines.append("|---|---|---|---|---|---|---|---|---|")
        for d in drifts:
            report_lines.append(
                f"| `{d['func']}` | `{d['module']}` | `{d['parent_func']}` | {d['call_count']} | "
                f"+{d['slope_mb_per_inv']:.2f} | +{d['net_drift_mb']:.1f} MB | {d['start_ram_mb']:.1f} | "
                f"{d['end_ram_mb']:.1f} | inv #{d['divergence_inv_idx']} |"
            )
        report_lines.append("")
    else:
        report_lines.append("No call sites exceeded the drift threshold (`> 3.0 MB/inv` with `R² >= 0.5`).\n")

    # Section 4: Thrashing & Page Fault Spikes
    report_lines.append("## 4. Thrashing & Swap Pressure Events\n")
    if thrash:
        report_lines.append("| Function | Module | Inv # | PID | Time | Duration | RAM Peak | Commit Peak | Swap Ratio | Page Faults |")
        report_lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for t in thrash[:15]:
            report_lines.append(
                f"| `{t['func']}` | `{t['module']}` | {t['inv_idx']} | `{t['pid']}` | "
                f"{t['start_ts']} | {t['duration_ms']:.1f}ms | {t['ram_peak_mb']:.1f} MB | "
                f"{t['commit_peak_mb']:.1f} MB | {t['swap_pressure']:.2f} | {t['page_faults_delta']} |"
            )
        report_lines.append("")
    else:
        report_lines.append("No severe page fault spikes or swap pressure anomalies recorded.\n")

    # Section 5: Comparative Analysis (if requested)
    if compare_dir and Path(compare_dir).exists():
        comp_path = Path(compare_dir)
        df_diff = compare_runs(data_dir, comp_path)
        report_lines.append(f"## 5. Comparative Performance Diff: `{data_dir.name}` vs `{comp_path.name}`\n")
        report_lines.append(
            "> [!NOTE]\n"
            f"> **Run 1**: `{data_dir.name}`  \n"
            f"> **Run 2**: `{comp_path.name}`  \n"
            "> Negative `Δ RAM` indicates memory reduction in Run 2. Positive `Δ Dur %` indicates execution slowdown.\n"
        )
        report_lines.append("| Function | Module | Calls (R1 / R2) | Time R1 (s) | Time R2 (s) | Δ Time % | Peak RAM R1 | Peak RAM R2 | Δ Peak RAM |")
        report_lines.append("|---|---|---|---|---|---|---|---|---|")
        for _, diff in df_diff.head(20).iterrows():
            report_lines.append(
                f"| `{diff['func']}` | `{diff['module']}` | {diff['calls_r1']} / {diff['calls_r2']} | "
                f"{diff['total_s_r1']:.2f}s | {diff['total_s_r2']:.2f}s | {diff['diff_dur_pct']:+.1f}% | "
                f"{diff['peak_ram_r1']:.1f} MB | {diff['peak_ram_r2']:.1f} MB | {diff['diff_ram_mb']:+.1f} MB |"
            )
        report_lines.append("")

    report_text = "\n".join(report_lines)

    if output_report:
        output_report = Path(output_report)
        output_report.parent.mkdir(parents=True, exist_ok=True)
        output_report.write_text(report_text, encoding="utf-8")

    return report_text


def analyze_performance(
    data_dir: Path,
    compare_dir: Optional[Path] = None,
    report_path: Optional[Path] = None,
) -> None:
    """High-level analysis orchestrator called from CLI or harness."""
    data_dir = Path(data_dir)
    report_text = generate_markdown_report(data_dir, compare_dir, report_path)
    print("\n" + "=" * 70)
    try:
        print(report_text[:1200] + ("\n... [truncated for console]" if len(report_text) > 1200 else ""))
    except UnicodeEncodeError:
        print(report_text[:1200].encode("ascii", "replace").decode("ascii") + ("\n... [truncated for console]" if len(report_text) > 1200 else ""))
    print("=" * 70)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m src.devtools.tracing.trace_analyzer",
        description="Analyze star-schema performance traces for memory drift, thrashing, and comparative diffs.",
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        required=True,
        help="Directory containing call_sites.parquet and invocations.parquet.",
    )
    parser.add_argument(
        "--compare",
        type=str,
        default=None,
        help="Optional second run directory for comparative differential analysis.",
    )
    parser.add_argument(
        "--report",
        type=str,
        default=None,
        help="Output markdown report file path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    report_p = Path(args.report) if args.report else None
    compare_p = Path(args.compare) if args.compare else None
    analyze_performance(data_dir=Path(args.data_dir), compare_dir=compare_p, report_path=report_p)


if __name__ == "__main__":
    main()
